sonar.host.url=https://sonarcloud.io

sonar.sources=serve-ease/src,serve-ease-admin/src
sonar.tests=serve-ease/tests,serve-ease-admin/tests
sonar.javascript.lcov.reportPaths=serve-ease/coverage/lcov.info,serve-ease-admin/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/test/**,**/*.test.*,**/*.spec.*
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/coverage/**
